version: "3.9"

services:
  laperme-frontend:
    container_name: laperme-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - laperme-net
    environment:
      NEXT_PUBLIC_URL_API_BACKEND: ${NEXT_PUBLIC_URL_API_BACKEND}
      NEXT_PUBLIC_API_KEY_TINYMCE: ${NEXT_PUBLIC_API_KEY_TINYMCE}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

networks:
  laperme-net:
    external: true
  
